#!/bin/bash
case "$1" in
    remove)
        # Remove configuration files
        rm -rf /etc/certificate_controller/

        # Remove logs
        rm -rf /var/log/certificate_controller/

	rm -rf /etc/logrotate.d/certificate_controller/

        # Remove binaries or additional directories
        rm -rf /usr/bin/certificate_controller/

        rm -rf /opt/certificate_controller_env/
        ;;
esac
exit 0

