#!/bin/bash

set -e

echo "Installation of python3 libraries"
pip install -r  /usr/share/certificate_controller/requirements.txt

case "$1" in
	configure)
		systemctl enable certificate_controller
		systemctl start certificate_controller
		;;
esac
