#!/bin/bash

set -e

echo "Installation of python3 libraries"
mkdir /var/log/certificate_controller/
python3 -m venv /opt/certificate_controller_env
source /opt/certificate_controller_env/bin/activate
pip install -r /usr/share/certificate_controller/requirements.txt

#pip install -r  /usr/share/certificate_controller/requirements.txt

case "$1" in
	configure)
		systemctl enable certificate_controller
		systemctl start certificate_controller
		;;
esac
